### ISSUE TITLE
HTTP 500 Error

### ISSUE THREAD

**Issue by mkinili** [Webcampak/core#7] opened 2021-01-18 10:40 UTC
Hi
Thanks for this app

Apparently bootstrap.php.cache is missing hence i am getting php HTTP 500 issue. Can someone please help?

Matt

**Comment by Fgerthoffert** [comment] 2021-02-02 00:18
I couldn't reproduce the issue starting from a fresh Webcampak install.

Since the issue appears to be fixed according to our other discussion, I'm going to close this ticket.

**Closed as completed by Fgerthoffert** 2021-02-02 00:18 UTC
